# 운영 RDS DB 연결 설정 (SSL 활성화 및 비관적 락 오작동 방지 세션 설정 추가)
spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/coupondb?sslMode=trust&sessionVariables=innodb_snapshot_isolation=OFF
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 운영 환경용 테이블 설정 (기존 데이터 보존을 위해 구조 자동 변경 방지)
spring.jpa.hibernate.ddl-auto=validate
