# 로컬 개발용 DB 연결 설정 (SSL 비활성화)
spring.datasource.url=jdbc:mariadb://localhost:3306/coupondb
spring.datasource.username=test
spring.datasource.password=1234

# 로컬 개발 시 테이블 자동 업데이트
spring.jpa.hibernate.ddl-auto=update
