spring.application.name=coupon-system
spring.profiles.active=local

# 1. MariaDB 드라이버 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 2. JPA 및 하이버네이트 설정
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
