# 운영 RDS DB 연결 설정 (SSL 활성화)
spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/coupondb?sslMode=trust
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 운영 환경용 테이블 설정 (기존 데이터 보존을 위해 구조 자동 변경 방지)
spring.jpa.hibernate.ddl-auto=validate
